In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2], index = ['T','U','V'])

ser2 = Series([3,4], index = ['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
# Concat in pandas
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2], axis = 1)  # it also creates a dataframe

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2], keys = ['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns = ['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3), columns = ['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0 -0.661616 -0.697580  1.223974
1 -0.228259  0.570489  0.140545
2  0.303063 -0.308654 -1.567032
3 -0.573360  0.069314 -0.596595

In [14]:
dframe2

Y         Q         X
0  1.774550 -1.575549  0.343680
1 -1.290302  0.391411 -1.110587
2  1.440506  0.440802  0.989873

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.661616 -0.697580  1.223974
1       NaN -0.228259  0.570489  0.140545
2       NaN  0.303063 -0.308654 -1.567032
3       NaN -0.573360  0.069314 -0.596595
0 -1.575549  0.343680  1.774550       NaN
1  0.391411 -1.110587 -1.290302       NaN
2  0.440802  0.989873  1.440506       NaN

In [16]:
pd.concat([dframe1,dframe2], ignore_index = True)

Q         X         Y         Z
0       NaN -0.661616 -0.697580  1.223974
1       NaN -0.228259  0.570489  0.140545
2       NaN  0.303063 -0.308654 -1.567032
3       NaN -0.573360  0.069314 -0.596595
4 -1.575549  0.343680  1.774550       NaN
5  0.391411 -1.110587 -1.290302       NaN
6  0.440802  0.989873  1.440506       NaN

In [17]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'

In [ ]:
## np.concatenate    In numpy
# pd.concat         In pandas