In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)   # random normal distribution

In [7]:
A

array([ 0.88931311, -0.44841445, -0.50496441, -0.16306087,  0.27633121,
        0.31486274,  0.78809999,  1.50609656,  2.33281188,  0.94623151])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 0.94654158,  1.29437749, -0.25859537,  2.17182104, -2.05954983,
        0.06635477,  1.10296144, -0.62687917,  0.68367055, -0.60425319])

In [11]:
# Binary Functions
np.add(A,B)

array([ 1.83585469,  0.84596304, -0.76355978,  2.00876017, -1.78321861,
        0.3812175 ,  1.89106143,  0.87921739,  3.01648244,  0.34197832])

In [12]:
0.946+0.8893

1.8353

In [13]:
np.maximum(A,B)

array([ 0.94654158,  1.29437749, -0.25859537,  2.17182104,  0.27633121,
        0.31486274,  1.10296144,  1.50609656,  2.33281188,  0.94623151])

In [14]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

import webbrowser
webbrowser.open(website)

True